baseURL: /
languageCode: en-us
title: Futusol
DefaultContentLanguage: ee

menu:
  main:
    - name: Futusol
      identifier: futusol
      url: /
      weight: 1
params:
  showActiveNav: true 
  footerText: Copyright © 2020 Futusol. Kõik õigused kaitstud.


